nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin:
            - 'http://localhost:8080' 
            - 'https://monappclient.com' 
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE']
