version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    environment:
      - SYMFONY_ENV=dev
      - DATABASE_URL=pgsql://postgres:password@db:5432/gmail
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: symfony_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gmail
    ports:
      - "5432:5432"
